name:                 coapplicative
version:              0.0.2
visibility:           public
id:                   coapplicative-0.0.2-inplace
key:                  coapplicative-0.0.2-inplace
license:              BSD-3-Clause
copyright:            2020 Chris McKinlay
maintainer:           Chris McKinlay
author:               Chris McKinlay
stability:            Experimental
homepage:             https://github.com/cmk/coapplicative
synopsis:             Coapplicative functors
description:          Coapplicative and partially distributive functors
category:             Data, Structures
abi:                  inplace
exposed:              True
exposed-modules:      Control.Coapplicative Data.Functor.Coapply
import-dirs:
    /Users/cmk/Documents/Code/haskell/fault/dist-newstyle/build/x86_64-osx/ghc-9.6.7/coapplicative-0.0.2/build

library-dirs:
    /Users/cmk/Documents/Code/haskell/fault/dist-newstyle/build/x86_64-osx/ghc-9.6.7/coapplicative-0.0.2/build

library-dirs-static:
    /Users/cmk/Documents/Code/haskell/fault/dist-newstyle/build/x86_64-osx/ghc-9.6.7/coapplicative-0.0.2/build

dynamic-library-dirs:
    /Users/cmk/Documents/Code/haskell/fault/dist-newstyle/build/x86_64-osx/ghc-9.6.7/coapplicative-0.0.2/build

data-dir:             /Users/cmk/Documents/Code/haskell/coapplicative/.
hs-libraries:         HScoapplicative-0.0.2-inplace
depends:
    base-4.18.3.0 smgrpds-6.0.2-d3774045 tggd-0.8.10-8ac42ba3
    transformers-0.6.1.0

haddock-interfaces:
    /Users/cmk/Documents/Code/haskell/fault/dist-newstyle/build/x86_64-osx/ghc-9.6.7/coapplicative-0.0.2/doc/html/coapplicative/coapplicative.haddock

haddock-html:
    /Users/cmk/Documents/Code/haskell/fault/dist-newstyle/build/x86_64-osx/ghc-9.6.7/coapplicative-0.0.2/doc/html/coapplicative
