name:                 profunctor-optics
version:              0.0.3
visibility:           public
id:                   profunctor-optics-0.0.3-inplace
key:                  profunctor-optics-0.0.3-inplace
license:              BSD-3-Clause
copyright:            2019-2026 Chris McKinlay
maintainer:           Chris McKinlay
author:               Chris McKinlay
stability:            Experimental
homepage:             https://github.com/cmk/profunctor-optics
synopsis:
    A compact optics library compatible with the typeclasses in profunctors.

description:
    This package provides utilities for creating and manipulating profunctor-based optics. Some highlights:

    Full complement of isos, prisms, lenses, grates, traversals, cotraversals, views, setters, folds, and more.

    Compact & straight-forward implementation.

    Fully interoperable. All that is required to create optics is the @profunctors@ package. Optics compose with @(.)@ from @Prelude@ as is typical. Conversions to & from the Van Laarhoven representations are provided for each optic type.

    See the <https://github.com/cmk/profunctor-optics#readme README> for more information.

category:             Data, Lenses, Profunctors
abi:                  inplace
exposed:              True
exposed-modules:
    Data.Functor.Adjunction from djnctns-4.4.4-78e387fe:Data.Functor.Adjunction,
    Data.Functor.Rep from djnctns-4.4.4-78e387fe:Data.Functor.Rep,
    Data.Profunctor.Optic, Data.Profunctor.Optic.Carrier,
    Data.Profunctor.Optic.Combinator, Data.Profunctor.Optic.Fold,
    Data.Profunctor.Optic.Iso, Data.Profunctor.Optic.Lens,
    Data.Profunctor.Optic.Prism, Data.Profunctor.Optic.Property,
    Data.Profunctor.Optic.Setter, Data.Profunctor.Optic.Traversal,
    Data.Profunctor.Optic.Types, Data.Profunctor.Optic.View

hidden-modules:       Data.Profunctor.Optic.Import
import-dirs:
    /Users/cmk/Documents/Code/haskell/fault/dist-newstyle/build/x86_64-osx/ghc-9.6.7/profunctor-optics-0.0.3/build

library-dirs:
    /Users/cmk/Documents/Code/haskell/fault/dist-newstyle/build/x86_64-osx/ghc-9.6.7/profunctor-optics-0.0.3/build

library-dirs-static:
    /Users/cmk/Documents/Code/haskell/fault/dist-newstyle/build/x86_64-osx/ghc-9.6.7/profunctor-optics-0.0.3/build

dynamic-library-dirs:
    /Users/cmk/Documents/Code/haskell/fault/dist-newstyle/build/x86_64-osx/ghc-9.6.7/profunctor-optics-0.0.3/build

data-dir:
    /Users/cmk/Documents/Code/haskell/profunctor-optics/profunctor-optics/.

hs-libraries:         HSprofunctor-optics-0.0.3-inplace
depends:
    djnctns-4.4.4-78e387fe base-4.18.3.0 coapplicative-0.0.2-inplace
    dstrbtv-0.6.3-a104a323 mtl-2.3.1 prfnctrs-5.6.3-0d8d86e4
    smgrpds-6.0.2-d3774045 tggd-0.8.10-8ac42ba3 transformers-0.6.1.0

haddock-interfaces:
    /Users/cmk/Documents/Code/haskell/fault/dist-newstyle/build/x86_64-osx/ghc-9.6.7/profunctor-optics-0.0.3/doc/html/profunctor-optics/profunctor-optics.haddock

haddock-html:
    /Users/cmk/Documents/Code/haskell/fault/dist-newstyle/build/x86_64-osx/ghc-9.6.7/profunctor-optics-0.0.3/doc/html/profunctor-optics
